### ISSUE TITLE
How to use MpbPPI to predict point mutations of a pdb files?

### ISSUE THREAD

**Issue by kehan777** [arantir123/MpbPPI#1]
Hello, Would you tell me how to use MpbPPI to predict point mutations of a pdb file?
for example,GeoPPI, https://github.com/Liuxg16/GeoPP 
using: python run.py data/testExamples/1PPF.pdb  TI17F  E_I;
how to use MpbPPI ?

**Comment by arantir123** [comment]
Hi, currently there is no single script of processing single raw pdb file from scratch provided in this repository, maybe you could adjust my scripts for your own use purpose. I hope I could have some time to write such a script in the future.
