### ISSUE TITLE
[MpbPPI] A request for the 10-fold cross-validation dataset split files ( S645 and S1131) 

### ISSUE THREAD

**Issue by LIU-CT** [arantir123/MpbPPI#2]
Very happy to contact you. 

MpbPPI is a very creative work to predict the effect of mutations on protein–protein interactions and creatively integrate the mutant structure predicted by the mutant structure generation tools to improve the performance. 
Upon delving into this work, I observed that the files for the 10-fold cross-validation splits of datasets S4169 and M1101 have been thoughtfully provided. However, it seems that the dataset split files for datasets S645 and S1131 have not been uploaded. 
Could you kindly furnish the 10-fold cross-validation dataset split files for these two datasets? Your assistance in this matter would be immensely valuable.

Thanks so much for your support. I'm looking forward to your reply.

**Comment by arantir123** [comment]
Hi,

Thank you very much for your encouragement. I have uploaded the 10-fold cross-validation dataset split files for S645 and S1131 based on the same splitting random seed as those for M1101 and S4169: https://github.com/arantir123/MpbPPI/tree/main/data.
